# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - db_data:/app/db  # garante persistência do SQLite
    environment:
      - ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: busybox
    volumes:
      - db_data:/data/db
    command: sh -c "echo 'Volume para dados criado' && sleep 3600"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

# ✅ VOLUMES CORRETOS: SEM HÍFENS, APENAS NOMES
volumes:
  db_data:
  node_modules: